Repository 21TORR/StoryblokBundle, pull requests merged in 2023-04, with the labels that each got.

#58 Add console command `storyblok:components:overview`
  CHANGELOG.md
  src/Api/Data/ComponentIdMap.php
  src/Api/ManagementApi.php
  src/Command/ComponentsOverviewCommand.php
Labels: enhancement

#59 Fix empty check in `RichTextField`
  CHANGELOG.md
  src/Field/Definition/RichTextField.php
Labels: bug

#60 Allow value-objects to be returned from `CompositeField::transformData()`
  CHANGELOG.md
  src/Field/Group/AbstractGroupingElement.php
  src/Field/Group/CompositeField.php
Labels: enhancement

#61 Transform RTE bloks data
  CHANGELOG.md
  src/Field/Definition/RichTextField.php
Labels: enhancement

#63 Add new `RichTextStyling` options
  CHANGELOG.md
  src/Field/RichText/RichTextStyling.php
Labels: enhancement

#64 Show space id when syncing definitions
  CHANGELOG.md
  src/Command/SyncDefinitionsCommand.php
  src/Config/StoryblokConfig.php
Labels: enhancement

#65 Enable dry run by default for sync command
  CHANGELOG.md
  src/Command/SyncDefinitionsCommand.php
  src/Manager/Sync/ComponentSync.php
Labels: enhancement

#67 Add possibility to load info about the current space
  CHANGELOG.md
  src/Api/ContentApi.php
  src/Api/Data/SpaceInfo.php
Labels: enhancement

#68 Fix circular service definition
  src/Context/ComponentContext.php
Labels: bug

#69 Show more info sync on sync + refactor implementation
  CHANGELOG.md
  src/Command/SyncDefinitionsCommand.php
Labels: enhancement

#70 Prepare release 3.0.0-beta.1
  CHANGELOG.md
  UPGRADE.md
Labels: documentation
